version: '1'
services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pa55w0rd2022"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
  my-api:
    build: .
    environment:
      DBServer: "ms-sql-server"
    ports:
     - "8080:8080"
  identity-server: 
    build: "C:/Users/Admin/Desktop/my-full-shop/IdentityServer/IdentityServer.WebApplication/WebApplication.Testing.Features/"
    image: "identity1"
    ports:
     - "59001:80"
